src/Entity/Seeder.php
<?php

namespace App\Entity;

use App\Repository\SeederRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SeederRepository::class)]
class Seeder
{
    #[ORM\Id]
    #[ORM\GeneratedValue()]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\OneToMany(targetEntity: Seed::class, mappedBy: 'seeder')]
    private Collection $seeds;

    public function __construct()
    {
        $this->seeds = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, Seed>
     */
    public function getSeeds(): Collection
    {
        return $this->seeds;
    }

    public function addSeed(Seed $seed): static
    {
        if (!$this->seeds->contains($seed)) {
            $this->seeds->add($seed);
            $seed->setSeeder($this);
        }

        return $this;
    }

    public function removeSeed(Seed $seed): static
    {
        if ($this->seeds->removeElement($seed)) {
            // set the owning side to null (unless already changed)
            if ($seed->getSeeder() === $this) {
                $seed->setSeeder(null);
            }
        }

        return $this;
    }
}

src/Entity/Strain.php
<?php

namespace App\Entity;

use App\Repository\StrainRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StrainRepository::class)]
class Strain
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'strains')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Breeder $breeder = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $name_id = null;

    #[ORM\Column]
    private ?bool $auto = null;

    #[ORM\Column(nullable: true)]
    private ?int $duration = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $type = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $url_photo = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $descriptionen = null;

    #[ORM\ManyToOne(inversedBy: 'strains')]
    private ?User $userid = null;

    #[ORM\Column(length: 500, nullable: true)]
    private ?string $logo = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBreeder(): ?Breeder
    {
        return $this->breeder;
    }

    public function setBreeder(?Breeder $breeder): static
    {
        $this->breeder = $breeder;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getNameId(): ?string
    {
        return $this->name_id;
    }

    public function setNameId(string $name_id): static
    {
        $this->name_id = $name_id;

        return $this;
    }

    public function isAuto(): ?bool
    {
        return $this->auto;
    }

    public function setAuto(bool $auto): static
    {
        $this->auto = $auto;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(?int $duration): static
    {
        $this->duration = $duration;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getUrlPhoto(): ?string
    {
        return $this->url_photo;
    }

    public function setUrlPhoto(?string $url_photo): static
    {
        $this->url_photo = $url_photo;

        return $this;
    }

    public function getDescriptionen(): ?string
    {
        return $this->descriptionen;
    }

    public function setDescriptionen(?string $descriptionen): static
    {
        $this->descriptionen = $descriptionen;

        return $this;
    }

    public function __toString(): string
    {
        return $this->name;
    }

    public function getUserId(): ?User
    {
        return $this->userid;
    }

    public function setUserId(?User $userid): static
    {
        $this->userid = $userid;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): static
    {
        $this->logo = $logo;

        return $this;
    }
}

src/Form/SeederType.php
<?php

namespace App\Form;

use App\Entity\Seeder;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SeederType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Seeder::class,
        ]);
    }
}

src/Controller/SeederController.php
<?php

namespace App\Controller;

use App\Entity\Seeder;
use App\Form\SeederType;
use App\Repository\SeederRepository;
use App\Entity\Breeder;
use App\Entity\Strain;
use App\Repository\BreederRepository;
use App\Service\DatatablesServiceInterface;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Contracts\HttpClient\HttpClientInterface;

#[Route('/seeder', name: 'app_seeder_')]
#[IsGranted('ROLE_USER')]
class SeederController extends AbstractController
{
    #[Route('', name: 'index', methods: ['GET'])]
    public function index(EntityManagerInterface $entityManager, BreederRepository $breederRepository, HttpClientInterface $httpClient): Response
    {
        return $this->render('seeder/index.html.twig', [
            'breeders'   => $breederRepository->findBy([], ['name' => 'asc']),
            'nav'       => 'seeder',
        ]);
    }

    #[Route('/new', name: 'new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $seeder = new Seeder();
        $form = $this->createForm(SeederType::class, $seeder);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($seeder);
            $entityManager->flush();

            return $this->redirectToRoute('app_seeder_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('seeder/new.html.twig', [
            'seeder'    => $seeder,
            'form'      => $form,
            'nav'       => 'seeder'
        ]);
    }

    #[Route('/ajaxseeders', name: 'ajax')]
    public function ajaxSeeders(Request $request, DatatablesServiceInterface $datatablesService): JsonResponse
    {
        $queryResult = $datatablesService->getData('Breeder', $request);
        $queryResult['admin'] = false;
        if (in_array('ROLE_ADMIN', $this->getUser()->getRoles(), true)) {
            $queryResult['admin'] = true;
        }
        return new JsonResponse($queryResult);
    }

    #[Route('/{id}', name: 'show', methods: ['GET'])]
    public function show(Seeder $seeder): Response
    {
        return $this->render('seeder/show.html.twig', [
            'seeder'    => $seeder,
            'nav'       => 'seeder'
        ]);
    }

    #[Route('/{id}/edit', name: 'edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Seeder $seeder, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(SeederType::class, $seeder);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_seeder_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('seeder/edit.html.twig', [
            'seeder'    => $seeder,
            'form'      => $form,
            'nav'       => 'seeder'
        ]);
    }

    #[Route('/{id}', name: 'delete', methods: ['POST'])]
    public function delete(Request $request, Seeder $seeder, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$seeder->getId(), $request->request->get('_token'))) {
            $entityManager->remove($seeder);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_seeder_index', [], Response::HTTP_SEE_OTHER);
    }


}

templates/seeder/_delete_form.html.twig
<form method="post" action="{{ path('app_seeder_delete', {'id': seeder.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ seeder.id) }}">
    <button class="btn">Delete</button>
</form>

templates/seeder/base.html.twig
{% extends 'base.html.twig' %}
{% block javascripts %}
    {% block importmap %}{{ importmap('seeders') }}{% endblock %}
{% endblock %}

templates/seeder/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Seeder{% endblock %}

{% block body %}
    <h1>Edit Seeder</h1>

    {{ include('seeder/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_seeder_index') }}">back to list</a>

    {{ include('seeder/_delete_form.html.twig') }}
{% endblock %}

templates/seeder/index.html.twig
{% extends 'seeder/base.html.twig' %}

{% block title %}Seeder index{% endblock %}

{% block body %}
    <table class="table datatables stripe" data-url="{{ path('app_seeder_ajax') }}">
        <thead>
        <tr>
            <th class="header_action"></th>
            <th>Name</th>
        </tr>
        </thead>
        {#<tbody>
        {% for breeder in breeders %}
            <tr style="height: 100px; vertical-align: middle;">
                <td class="table_col_action">
                    <a href="{{ path('app_seeder_show', {'id': breeder.id}) }}"><i
                            class="bi bi-eye button_action"></i></a>
                    <a href="{{ path('app_seeder_edit', {'id': breeder.id}) }}"><i
                            class="bi bi-pencil-square button_action"></i></a>
                </td>
                <td><img src="{{ breeder.urlPhoto }}" alt="" style="max-width: 100px;"></td>
                <td>{{ breeder.name }} ({{ breeder.strains|length }})</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>#}
    </table>

    <a href="{{ path('app_seeder_new') }}">Create new</a>
{% endblock %}

templates/seeder/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Seeder{% endblock %}

{% block body %}
    <h1>Create new Seeder</h1>

    {{ include('seeder/_form.html.twig') }}

    <a href="{{ path('app_seeder_index') }}">back to list</a>
{% endblock %}

templates/seeder/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Seeder{% endblock %}

{% block body %}
    <h1>Seeder</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ seeder.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ seeder.name }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_seeder_index') }}">back to list</a>

    <a href="{{ path('app_seeder_edit', {'id': seeder.id}) }}">edit</a>

    {{ include('seeder/_delete_form.html.twig') }}
{% endblock %}