src/Entity/MyPlants.php
<?php

namespace App\Entity;

use App\Entity\Traits\TimeStampableTrait;
use App\Repository\MyPlantsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MyPlantsRepository::class)]
class MyPlants
{
    use TimeStampableTrait;
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'myPlants')]
    #[ORM\JoinColumn(nullable: false)]
    private ?MySeeds $my_seeds = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $name = null;

    #[ORM\Column(nullable: true)]
    private ?int $duration = null;



    #[ORM\ManyToOne(inversedBy: 'myPlants')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $userid = null;

    #[ORM\Column(nullable: false)]

    private bool $finished = false;

    #[ORM\OneToOne(mappedBy: 'my_plants', cascade: ['persist', 'remove'])]
    private ?Germination $germination = null;

    #[ORM\OneToOne(mappedBy: 'my_plants', cascade: ['persist', 'remove'])]
    private ?Growths $growths = null;

    #[ORM\OneToOne(mappedBy: 'my_plants',cascade: ['persist', 'remove'])]
    private ?Preblooms $preblooms;

        #[ORM\OneToOne( mappedBy: 'my_plants', cascade: ['persist', 'remove'])]
    private ?Blooms $blooms;

    #[ORM\OneToOne(mappedBy: 'my_plants', cascade: ['persist', 'remove'])]
    private Harvests $harvests;


    public function __construct()
    {
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMySeeds(): ?MySeeds
    {
        return $this->my_seeds;
    }

    public function setMySeeds(?MySeeds $my_seeds): static
    {
        $this->my_seeds = $my_seeds;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(?int $duration): static
    {
        $this->duration = $duration;

        return $this;
    }

    public function getUserid(): ?User
    {
        return $this->userid;
    }

    public function setUserid(?User $userid): static
    {
        $this->userid = $userid;

        return $this;
    }

    public function isFinished(): ?bool
    {
        return $this->finished;
    }

    public function setFinished(bool $finished = false): static
    {
        $this->finished = $finished;

        return $this;
    }

    public function getGermination(): ?Germination
    {
        return $this->germination;
    }

    public function setGermination(?Germination $germination): void
    {
        $this->germination = $germination;
    }

    public function getGrowths(): ?Growths
    {
        return $this->growths;
    }

    public function setGrowths(?Growths $growths): void
    {
        $this->growths = $growths;
    }

    public function getPreblooms(): ?Preblooms
    {
        return $this->preblooms;
    }

    public function setPreblooms(?Preblooms $preblooms): void
    {
        $this->preblooms = $preblooms;
    }

    public function getBlooms(): ?Blooms
    {
        return $this->blooms;
    }

    public function setBlooms(?Blooms $blooms): void
    {
        $this->blooms = $blooms;
    }

    public function getHarvests(): Harvests
    {
        return $this->harvests;
    }

    public function setHarvests(Harvests $harvests): void
    {
        $this->harvests = $harvests;
    }


}

src/Entity/Seed.php
<?php

namespace App\Entity;

use App\Repository\SeedRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SeedRepository::class)]
class Seed
{
    #[ORM\Id]
    #[ORM\GeneratedValue()]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\ManyToOne(inversedBy: 'seeds')]
    private ?Seeder $seeder = null;

    #[ORM\ManyToOne(inversedBy: 'seeds')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $userid = null;

    #[ORM\Column]
    private ?int $Quantity = null;

    #[ORM\Column]
    private ?int $Duration = null;

    #[ORM\OneToMany(targetEntity: Plant::class, mappedBy: 'seedid', fetch: 'EAGER', orphanRemoval: true)]
    private Collection $plants;

    public function __construct()
    {
        $this->plants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSeeder(): ?Seeder
    {
        return $this->seeder;
    }

    public function setSeeder(?Seeder $seeder): static
    {
        $this->seeder = $seeder;

        return $this;
    }

    public function getUserid(): ?User
    {
        return $this->userid;
    }

    public function setUserid(?User $userid): static
    {
        $this->userid = $userid;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->Quantity;
    }

    public function setQuantity(int $Quantity): static
    {
        $this->Quantity = $Quantity;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->Duration;
    }

    public function setDuration(int $Duration): static
    {
        $this->Duration = $Duration;

        return $this;
    }

    /**
     * @return Collection<int, Plant>
     */
    public function getPlants(): Collection
    {
        return $this->plants;
    }

    public function addPlant(Plant $plant): static
    {
        if (!$this->plants->contains($plant)) {
            $this->plants->add($plant);
            $plant->setSeedid($this);
        }

        return $this;
    }

    public function removePlant(Plant $plant): static
    {
        if ($this->plants->removeElement($plant)) {
            // set the owning side to null (unless already changed)
            if ($plant->getSeedid() === $this) {
                $plant->setSeedid(null);
            }
        }

        return $this;
    }
}

src/Controller/MyPlantsController.php
<?php

namespace App\Controller;

use App\Entity\EnumStates;
use App\Entity\Germination;
use App\Entity\MyPlants;
use App\Entity\Growths;
use App\Entity\Preblooms;
use App\Entity\Blooms;
use App\Entity\Harvests;
use App\Form\ChangeStateMyPlantsType;
use App\Form\DeletePlantType;
use App\Form\MyPlantsType;
use App\Repository\GerminationRepository;
use App\Repository\MyPlantsRepository;
use App\Repository\MySeedsRepository;
use App\Service\DatatablesServiceInterface;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Doctrine\DBAL\Exception;

#[Route('/myplants', name: 'app_my_plants_')]
class MyPlantsController extends AbstractController
{
    #[Route('', name: 'index')]
    public function index(): Response
    {
        return $this->render('my_plants/index.html.twig', [
            'controller_name' => 'MyPlantsController',
        ]);
    }

    #[Route('/add', name: 'add')]
    public function add(Request $request, MySeedsRepository $mySeedsRepository, EntityManagerInterface $entityManager): JsonResponse|RedirectResponse
    {

        $myplant = new MyPlants();
        if ($idseed = array_key_exists('my_plants', $request->request->all()) ? $request->request->all()['my_plants']['seedid'] : $request->request->get('id')) {
            try {
                $myseed = $mySeedsRepository->find((int)$idseed);
            } catch (Exception $e) {
                $errorMessage = $e->getMessage();
            }

            $myplant->setMySeeds($myseed);
        }

        $form = $this->createForm(MyPlantsType::class, $myplant, [
            'require_seed_id' => $idseed,
            'action' => $this->generateUrl('app_my_plants_add'),
            'method' => 'POST',
            'data' => $myplant
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            $germination = new Germination();
            $germination->setMyPlants($myplant);
            $dategerm = \DateTimeImmutable::createFromFormat('Y-m-d',$request->request->all()['my_plants']['date_germination']);
            $germination->setUserid($this->getUser());

            $germination->setDateActive($dategerm);

            $germination->setFinished(false);
            $myseed->setQuantity($myseed->getQuantity() - 1);
            $entityManager->persist($myplant);

            $entityManager->persist($germination);
            $entityManager->flush();
            return $this->redirectToRoute('app_my_seeds_index', [], Response::HTTP_SEE_OTHER);
        }
        $viewForm = $this->render('my_plants/_form.html.twig', [
            'form' => $form->createView()
        ]);
        return new JsonResponse(['form' => $viewForm->getContent()]);
    }

    #[Route('/count/{state}', name: 'count')]
    public function count(string $state, EntityManagerInterface $entityManager, MyPlantsRepository $myPlantsRepository, Security $security): Response
    {
        $count = 0;
        if (class_exists("App\\Entity\\" . $state)) {
            $repo = $entityManager->getRepository("App\\Entity\\" . $state);
            $count = $repo->countPlantsByState($this->getUser()->getId());
        } else if ($state == 'all') {
            $req = $myPlantsRepository->findBy(['userid' => $security->getUser(), 'finished' => false]);
            $count = count($req);
        }

        return new Response($count);
    }

    #[Route('/{slug}/list', name: 'list')]
    public function myplantsList(string $slug, EntityManagerInterface $entityManager, Security $security): Response
    {
        return $this->render('my_plants/index.html.twig', [
            'entity_name' => $slug,
            'nav' => 'plant'
        ]);
    }

    #[Route('/ajaxmyplants', name: 'ajax')]
    public function ajaxMyPlants(Request $request, EntityManagerInterface $entityManager, Security $security, DatatablesServiceInterface $datatablesService, MyPlantsRepository $myPlantsRepository, GerminationRepository $germinationRepository): JsonResponse
    {
        $entity = $request->request->get('entity');
        $result = [];
        if (class_exists("App\\Entity\\" . $entity)) {
            $repo = $entityManager->getRepository("App\\Entity\\" . $entity);
            $data = $repo->findBy(['userid' => $security->getUser(), 'finished' => false]);

            $result = $datatablesService->formatData($data, $request);
        }

        return new JsonResponse($result);
    }

    #[Route('/ajaxallmyplants', name: 'all_ajax')]
    public function ajaxAllMyPlants(Request $request, MyPlantsRepository $myPlantsRepository): JsonResponse
    {
        $entity = $request->request->get('entity');

        $result = [];
        $result['draw'] = $request->request->get('draw');
        if ($entity === 'all') {
            $myPlants = $myPlantsRepository->getAll();
            $result['recordsFiltered'] = count($myPlants);
            $result['recordsTotal'] = count($myPlants);
            $result['data'] = $myPlants;

        }

        return new JsonResponse($result);
    }

    #[Route('/changestate', name: 'changestate')]
    public function changeState(Request $request, EntityManagerInterface $entityManager, Security $security): JsonResponse|RedirectResponse
    {
        $dataAll = $request->request->all();

        $state = $request->request->get('state') ?: $dataAll['change_state_my_plants']['state'];
        $keyCurrentStep = array_search($state, $arraySteps = EnumStates::toArray());
        $idMyPlant = $request->request->get('id') ?: $dataAll['change_state_my_plants']['idmyplants'];
        if($state !== "all"){
            $repo = $entityManager->getRepository(("App\\Entity\\" . $state));
            $dataInfo = $repo->find($idMyPlant);
            $myPlant = $dataInfo->getMyPlants();
        }else{
            $myPlant = $entityManager->getRepository(("App\\Entity\\MyPlants"))->findOneBy(['id' => (int) $idMyPlant, 'userid' => $security->getUser()]);
            if($myPlant instanceof MyPlants) {
                $keyCurrentStep = 'GERM';
                $dataInfo = $myPlant->getGermination();
                if($myPlant->getGrowths()){
                    $keyCurrentStep = 'CROIS';
                    $dataInfo = $myPlant->getGrowths();
                }
                if($myPlant->getPreblooms()){
                    $keyCurrentStep = 'PREFLO';
                    $dataInfo = $myPlant->getPreblooms();
                }
                if($myPlant->getBlooms()){
                    $keyCurrentStep = 'FLO';
                    $dataInfo = $myPlant->getBlooms();
                }
            }
        }

        $plantName = $myPlant->getName() ?: $myPlant->getMySeeds()->getStrain()->getName();
        while (key($arraySteps) !== $keyCurrentStep) next($arraySteps);
        $nextStep = next($arraySteps);
        $urlAction = $this->generateUrl('app_my_plants_changestate');

        $data = [
            'data' => [
                'newstate' => $nextStep,
                'idmyplant' => $idMyPlant,
                'state' => $state,
            ],
            'action' => $urlAction,
        ];

        $form = $this->createForm(ChangeStateMyPlantsType::class, null, $data);

        $form->handleRequest($request);
        if ($form->isSubmitted()) {

            $dataInfo->setFinished(true);
            $className = "\\App\\Entity\\" . $dataAll['change_state_my_plants']['newstate'];
            $new = new $className;
            $new->setDateActive(new \DateTimeImmutable($dataAll['change_state_my_plants']['date_active']));
            $new->setMyPlants($myPlant);
            $new->setFinished(false);
            if($new instanceof Harvests){
                $new->setWeight($dataAll['change_state_my_plants']['weight']);
                $new->setNotes($dataAll['change_state_my_plants']['notes']);
                $myPlant->setFinished(true);
            }
            $entityManager->persist($dataInfo);
            $entityManager->persist($new);
            $entityManager->persist($myPlant);
            $entityManager->flush();
            return $this->redirectToRoute('app_my_plants_list', ['slug' => $state]);
        }

        $view = $this->render('my_plants/_formchangestate.html.twig', [
            'form' => $form->createView(),
            'nextstep' => current($arraySteps),
            'plantname' => $plantName
        ]);
        return new JsonResponse([
            'form' => $view->getContent(),

        ]);
    }

    #[Route('/delete', name: 'delete')]
    public function delete(Request $request, EntityManagerInterface $entityManager): JsonResponse|RedirectResponse
    {
        $dataAll = $request->request->all();
        if(array_key_exists('delete_plant',$dataAll)){
            $idMyPlant = $dataAll['delete_plant']['idmyplants'];
            $state = $dataAll['delete_plant']['state'];
        }else{
            $idMyPlant = $dataAll['idmyplants'];
            $state = $dataAll['state'];
        }
        $data = [
            'data' => [
                'idmyplant' => $idMyPlant,
                'state' => $state,
            ],
            'action' => $this->generateUrl('app_my_plants_delete'),
        ];
        $repo = $entityManager->getRepository("\\App\\Entity\\".$state);
        $plant = $repo->find($idMyPlant);
        $myPlant = $plant->getMyPlants();
        $plantName= $myPlant->getName()?:$myPlant->getMySeeds()->getStrain()-getName();

        $form = $this->createForm(DeletePlantType::class,null,$data);
        $form->handleRequest($request);

        if($form->isSubmitted() && array_key_exists('delete_plant',$dataAll)){
            $plant->setFinished(true);
            $myPlant->setFinished(true);

templates/my_plants/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
{{ form_end(form) }}

templates/my_plants/_formchangestate.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
{{ form_end(form) }}
<span class="changestate">{{ 'modals.changestate.pass'|trans }} <b>{{ plantname }}</b> {{ 'modals.changestate.to'|trans }} {{ "common.#{  nextstep|lower }"|trans }}</span>

templates/my_plants/_formdelete.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
{{ form_end(form) }}
<span class="changestate">{{ plant_name }}</span>

templates/my_plants/_info.html.twig
{% import "macros/diaries_my_plants_history.html.twig" as my_plant_history %}
<div class="row">
    <div class="col-6">
        <div class="row">
            <div class="col-4 text-center">
                {% if my_plant.mySeeds.strain.breeder.logo %}
                    <img src="{{ asset(my_plant.mySeeds.strain.breeder.logo) }}" class="logo">
                {% else %}
                    <img src="{{ asset('img/no-img.png') }}" alt="nologo" class="logo" />
                {% endif %}
            </div>
            <div class="col-8">
                <div class="row info-text info-text-title">{{ my_plant.mySeeds.strain.breeder.name }}</div>
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="row ">
            <div class="col-4 text-center">
                {% if my_plant.mySeeds.strain.logo %}
                    <img src="{{ asset(my_plant.mySeeds.strain.logo) }}" class="logo">
                {% else %}
                    <img src="{{ asset('img/no-img.png') }}" alt="nologo" class="logo" />
                {% endif %}
            </div>
            <div class="col-8">
                <div class="row info-text info-text-title"><div class="col">{{ function_get_name(my_plant) }}</div></div>

            </div>
        </div>
    </div>
</div>
<hr class="info">
<div class="row">
    <div class="col-12">
        <div class="row "><div class="col">{{ 'modals.myplantsinfo.bloomduration'|trans }}<span class="info-text">{% if my_plant.duration == 0 %} {{ my_plant.mySeeds.strain.duration }} {% else %}{{ my_plant.duration}}{% endif %} {{ 'common.days'|trans }}</span></div></div>
        <div class="row "><div class="col">{{ 'modals.myplantsinfo.qtyremain'|trans }}<span class="info-text">{{ my_plant.mySeeds.quantity }}</span></div></div>
        <div class="row "><div class="col">Type: <span class="info-text">{{ my_plant.mySeeds.strain.type }}</span></div></div>
        {% if my_plant.mySeeds.strain.auto %}<div class="row info-text"><div class="col">{{ 'myseeds.index.table.head.auto'|trans }}</div></div>{% endif %}
    </div>
</div>
<hr class="info">
<div class="">
    {{ my_plant.mySeeds.strain.description|replace({'\\': ''})|raw }}
</div>
<hr class="info">
<div class="row" style="padding: 10px 10px 0 10px">
    {{ my_plant_history.diary(my_plant) }}
</div>

templates/my_plants/base.html.twig
{% extends 'base.html.twig' %}
{% block javascripts %}
    {% block importmap %}{{ importmap('myplants') }}{% endblock %}
{% endblock %}

templates/my_plants/index.html.twig
{% extends 'my_plants/base.html.twig' %}

{% block title %}{{ "common.#{ entity_name|lower }"|trans }}{% endblock %}

{% block body %}
    {% include('modals/modal_change_state.html.twig') %}
    {% include('modals/modal_delete.html.twig') %}
    {% include('modals/modal_my_plants_info.html.twig') %}
    <div class="content-base">
        <h1  class="title_my_plants">{{ "common.#{ entity_name|lower }"|trans }}</h1>
        {% if entity_name != 'all' %}
            <table class="table datatables bg-transparent" data-url="{{ path('app_my_plants_ajax') }}" data-noimg="{{ asset('img/no-img.png') }}" data-entity="{{ entity_name }}">
                <thead>
                <tr>
                    <th></th>

                    <th>{{ 'myplants.index.table.head.name'|trans }}</th>
                    <th>{{ 'myplants.index.table.head.seeder'|trans }}</th>
                    <th>{{ 'myplants.index.table.head.duration'|trans }}</th>
                    <th>{{ 'myplants.index.table.head.started'|trans }}</th>
                    {# <th>{{ 'myseeds.index.table.head.auto'|trans }}</th>
                    <th>Type</th>
                    <th>{{ 'myseeds.index.table.head.comment'|trans }}</th>
                    <th>Description</th>#}
                </tr>
                </thead>
            </table>
        {% else %}
            <table class="table datatables bg-transparent" data-url="{{ path('app_my_plants_all_ajax') }}" data-noimg="{{ asset('img/no-img.png') }}" data-entity="{{ entity_name }}">
                <thead>
                <tr>
                    <th></th>

                    <th>{{ 'myplants.index.table.head.name'|trans }}</th>
                    <th>{{ 'myplants.index.table.head.seeder'|trans }}</th>
                   <th>{{ 'myplants.index.table.head.state'|trans }}</th>
                     {#<th>{{ 'myseeds.index.table.head.started'|trans }}</th>#}
                    {# <th>{{ 'myseeds.index.table.head.auto'|trans }}</th>
                    <th>Type</th>
                    <th>{{ 'myseeds.index.table.head.comment'|trans }}</th>
                    <th>Description</th>#}
                </tr>
                </thead>
            </table>
        {% endif %}
    </div>
{% endblock %}