src/Entity/PlantHistory.php
<?php

namespace App\Entity;

use App\Repository\PlantHistoryRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PlantHistoryRepository::class)]
#[ORM\HasLifecycleCallbacks]
class PlantHistory
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'plantHistories')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Plant $plant_id = null;

    #[ORM\Column(type: "string", length: 255, enumType: EnumStates::class)]
    private EnumStates $state;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPlantId(): ?Plant
    {
        return $this->plant_id;
    }

    public function setPlantId(?Plant $plant_id): static
    {
        $this->plant_id = $plant_id;

        return $this;
    }

    public function getState(): EnumStates
    {
        return $this->state;
    }

    public function setState(EnumStates $state): static
    {
        $this->state = $state;

        return $this;
    }


    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    #[ORM\PrePersist]
    public function setDate(): static
    {
        $this->date = new \DateTimeImmutable();

        return $this;
    }
}

src/Controller/PlantHistoryController.php
<?php

namespace App\Controller;

use App\Entity\Plant;
use App\Repository\PlantHistoryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/planthistory')]
class PlantHistoryController extends AbstractController
{
    #[Route('', name: 'app_plant_history_list')]
    public function index(PlantHistoryRepository $plantHistoryRepository): Response
    {
        $plantHistories = $plantHistoryRepository->findAll();
        return $this->render('plant_history/list.html.twig', [
            'planthistories' => $plantHistories,
            'nav' => 'plant',
        ]);
    }

    #[Route('/{id}', name: 'app_plant_history')]
    public function getOne(Plant $plant, PlantHistoryRepository $plantHistoryRepository): Response
    {
        $plantHistories = $plantHistoryRepository->findBy(['plant_id' => $plant], ['date' => 'DESC']);
        return $this->render('plant_history/index.html.twig', [
            'planthistories' => $plantHistories,
        ]);
    }
}

templates/plant_history/index.html.twig
<div class="card dashboard">
    <div class="card-body">
        <h5 class="card-title">Historique</h5>
        <div class="activity">
            {% for planthistory in planthistories %}
            <div class="activity-item d-flex">
                <div class="activite-label">{{ planthistory.date|date("d/m/Y") }} &nbsp</div>
                <i class="bi bi-circle-fill activity-badge {{ planthistory.state.name|lower }} align-self-start"></i>
                <div class="activity-content">
                    {{ planthistory.state.value }}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

templates/plant_history/list.html.twig
{% extends 'plant/base.html.twig' %}

{% block title %}Plantes{% endblock %}

{% block body %}

    <table>
    {% for planthistory in planthistories %}
        <tr>
            <td>{{ planthistory.plantId.seedid.name }}</td>
            <td>{{ planthistory.state.value }}</td>
            <td>{{ planthistory.date|date('d/m/Y') }}</td>
        </tr>
    {% endfor %}
    </table>

{% endblock %}